services:
    endroid_behavior.admin.extension.publishable:
        class: Endroid\Bundle\BehaviorBundle\Admin\Extension\PublishableAdminExtension
        tags:
            - { name: sonata.admin.extension }

    endroid_behavior.filter.publishable:
        class: Endroid\Bundle\BehaviorBundle\Filter\PublishableFilter
        arguments: [ '@doctrine.orm.entity_manager' ]
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    endroid_behavior.event_listener.sluggable:
        class: Endroid\Bundle\BehaviorBundle\EventListener\SluggableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: onPrePersist }

    endroid_behavior.admin.extension.sortable:
        class: Endroid\Bundle\BehaviorBundle\Admin\Extension\SortableAdminExtension
        tags:
            - { name: sonata.admin.extension }

    endroid_behavior.event_listener.sortable:
        class: Endroid\Bundle\BehaviorBundle\EventListener\SortableListener
        tags:
            - { name: doctrine.event_listener, event: postPersist, method: onPostPersist }
            - { name: doctrine.event_listener, event: preUpdate, method: onPreUpdate }

    endroid_behavior.event_listener.timestampable:
        class: Endroid\Bundle\BehaviorBundle\EventListener\TimestampableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: onPrePersist }
            - { name: doctrine.event_listener, event: preUpdate, method: onPreUpdate }

    endroid_behavior.event_listener.traversable:
        class: Endroid\Bundle\BehaviorBundle\EventListener\TraversableListener
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata , method: onLoadClassMetadata }

    endroid_behavior.admin.extension.traversable:
        class: Endroid\Bundle\BehaviorBundle\Admin\Extension\TraversableAdminExtension
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: sonata.admin.extension }
